name: 'Run action'

on:
  workflow_dispatch:


jobs:  
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: dart-action/custom-dart-action@main
        with:
          input-value: 'Hello dart action.'
          github-token: ${{ secrets.GITHUB_TOKEN }}